loans:
  message: "Welcome to Eazybank loans related qa API's"
  contactDetails:
    name: "Sahmita - QA Lead"
    email: "sahmita@eazybank.com"
  onCallSupport:
    - (666) 342-1234
    - (666) 534-1345