loans:
  message: "Welcome to Eazybank loans related prod API's"
  contactDetails:
    name: "Aishwarya - Prod Owner"
    email: "aishwarya@eazybank.com"
  onCallSupport:
    - (888) 836-1234
    - (888) 829-1345