services:
  configserver:
      image: "sheetaldockerpractice/configserver:s6"
      container_name: configserver-ms
      ports:
        - "8071:8071"
      healthcheck:
        test: "curl --fail --silent localhost:8071/actuator/health/readiness | grep UP || exit 1"
        interval: 10s
        timeout: 5s
        retries: 10
        start_period: 10s
      deploy:
        resources:
          limits:
            memory: 700m
      networks:
        - sheetaldocker
  accounts:
    image: "sheetaldockerpractice/accounts:s6"
    container_name: accounts-ms
    ports:
      - "8080:8080"
      - "8081:8080"
    depends_on: 
      configserver:
        condition: service_healthy
    deploy:
      resources:
        limits:
          memory: 700m
    networks:
      - sheetaldocker
    environment:
      SPRING_APPLICATION_NAME: accounts
      SPRING_CONFIG_IMPORT: "configserver:http://configserver:8071/"
      SPRING_PROFILES_ACTIVE: default
  loans:
    image: "sheetaldockerpractice/loans:s6"
    container_name: loans-ms
    ports:
      - "8090:8090"
    depends_on: 
      configserver:
        condition: service_healthy
    deploy:
      resources:
        limits:
          memory: 700m
    networks:
      - sheetaldocker
    environment:
      SPRING_APPLICATION_NAME: loans
      SPRING_CONFIG_IMPORT: "configserver:http://configserver:8071/"
      SPRING_PROFILES_ACTIVE: default
  cards:
    image: "sheetaldockerpractice/cards:s6"
    container_name: cards-ms
    ports:
      - "9000:9000"
    depends_on: 
      configserver:
        condition: service_healthy
    deploy:
      resources:
        limits:
          memory: 700m
    networks:
      - sheetaldocker
    environment:
      SPRING_APPLICATION_NAME: cards
      SPRING_CONFIG_IMPORT: "configserver:http://configserver:8071/"
      SPRING_PROFILES_ACTIVE: default
networks:
  sheetaldocker:
    driver: "bridge"