services:
  accounts:
    image: "sheetaldockerpractice/accounts:s4"
    container_name: accounts-ms
    ports:
      - "8080:8080"
      - "8081:8080"
    deploy:
      resources:
        limits:
          memory: 700m
    networks:
      - sheetaldocker
  loans:
    image: "sheetaldockerpractice/loans:s4"
    container_name: loans-ms
    ports:
      - "8090:8090"
    deploy:
      resources:
        limits:
          memory: 700m
    networks:
      - sheetaldocker
  cards:
    image: "sheetaldockerpractice/cards:s4"
    container_name: cards-ms
    ports:
      - "9000:9000"
    deploy:
      resources:
        limits:
          memory: 700m
    networks:
      - sheetaldocker
networks:
  sheetaldocker:
    driver: "bridge"