services:
  rabbit:
    image: rabbitmq:4-management
    hostname: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    healthcheck:
      test: rabbitmq-diagnostics check_port_connectivity
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 5s
    # extends:
    #   file: common-config.yml
    #   service: network-deploy-service
    networks:
      - sheetaldocker

  configserver:
    image: "sheetaldockerpractice/configserver:s6"
    container_name: configserver-ms
    ports:
      - "8071:8071"
    depends_on:
      rabbit:
        condition: service_healthy
    healthcheck:
      test: "curl --fail --silent localhost:8071/actuator/health/readiness | grep UP || exit 1"
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 10s
    # extends:
    #   file: common-config.yml
    #   service: microservice-base-config
    environment:
      SPRING_RABBITMQ_HOST: "rabbit"
    networks:
      - sheetaldocker

  accounts:
    image: "sheetaldockerpractice/accounts:s6"
    container_name: accounts-ms
    ports:
      - "8080:8080"
    depends_on:
      configserver:
        condition: service_healthy
    environment:
      SPRING_APPLICATION_NAME: "accounts"
      SPRING_RABBITMQ_HOST: "rabbit"
      SPRING_PROFILES_ACTIVE: default
      SPRING_CONFIG_IMPORT: configserver:http://configserver:8071/
    # extends:
    #   file: common-config.yml
    #   service: microservice-configserver-config
    networks:
      - sheetaldocker

  loans:
    image: "sheetaldockerpractice/loans:s6"
    container_name: loans-ms
    ports:
      - "8090:8090"
    depends_on:
      configserver:
        condition: service_healthy
    environment:
      SPRING_APPLICATION_NAME: "loans"
      SPRING_RABBITMQ_HOST: "rabbit"
      SPRING_PROFILES_ACTIVE: default
      SPRING_CONFIG_IMPORT: configserver:http://configserver:8071/
    # extends:
    #   file: common-config.yml
    #   service: microservice-configserver-config
    networks:
      - sheetaldocker

  cards:
    image: "sheetaldockerpractice/cards:s6"
    container_name: cards-ms
    ports:
      - "9000:9000"
    depends_on:
      configserver:
        condition: service_healthy
    environment:
      SPRING_APPLICATION_NAME: "cards"
      SPRING_RABBITMQ_HOST: "rabbit"
      SPRING_PROFILES_ACTIVE: default
      SPRING_CONFIG_IMPORT: configserver:http://configserver:8071/
    # extends:
    #   file: common-config.yml
    #   service: microservice-configserver-config
    networks:
      - sheetaldocker

networks:
  sheetaldocker:
    driver: "bridge"